apiVersion: vyogo.tech/v1
kind: FrappeSite
metadata:
  name: onecx
  namespace: default
spec:
  benchRef:
    name: lenscx-bench
  siteName: onecx.localhost
  adminPasswordSecretRef:
    name: onecx-admin-password
  apps:
    - erpnext
    - payments
    - pdf_on_submit
  ingress:
    enabled: false
---
apiVersion: vyogo.tech/v1
kind: FrappeSite
metadata:
  name: twocx
  namespace: default
spec:
  benchRef:
    name: lenscx-bench
  siteName: twocx.localhost
  adminPasswordSecretRef:
    name: twocx-admin-password
  apps:
    - erpnext
    - payments
    - pdf_on_submit
  ingress:
    enabled: false
